<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>404 Page Not Found</title>
	<link type="text/css" rel="stylesheet" href="<?php echo $this->getCssUrl('404') ?>" />

</head>

<body>

	   <div class='wrapper'>
				<h1>404</h1>
				<h2>Page not found</h2>
        <a href="/">Homepage</a>
		</div>


</body>
</html>
