<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>Comments Project</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
			integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
			crossorigin="anonymous">
		<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/vue"></script>
		<script src="http://momentjs.com/downloads/moment.js"></script>
		<link rel="stylesheet" href="<?php echo $this->getCssUrl('style')?>" />
	</head>
	<body>
		<div id="app">
			<h1 class="text-center">Comments</h1>
			<h4>Write a Comment</h4>
			<comment-form parent_id="0" level="0"></comment-form>
			<comment-list v-for="(comment,index) in comments"
				v-bind:author="comment.author"
				v-bind:content="comment.content"
				v-bind:created_at="comment.created_at"
				v-bind:level="comment.level"
				v-bind:parent_id="comment.id"
				v-bind:hierarchy="comment.id"
				v-bind:is_last="index==comments.length-1"
				v-bind:children="comment.children"></comment-list>
		</div>
		<script type="text/javascript">
		// used to create url for sending ajax requests to backend
		var BASE_URL = '<?php echo $this->getBaseUrl();?>';
		</script>
		<script type="text/javascript" src="<?php echo $this->getJsUrl('commentCardComponent')?>"></script>
		<script type="text/javascript" src="<?php echo $this->getJsUrl('commentFormComponent')?>"></script>
		<script type="text/javascript" src="<?php echo $this->getJsUrl('commentListComponent')?>"></script>
		<script type="text/javascript" src="<?php echo $this->getJsUrl('App')?>"></script>
	</body>
</html>
